### PR TITLE
#34 - Don't dispose UDP client after each message send.

### PR DESCRIPTION
**Pull request by Aenima4six2**

### CODE REVIEW

**Comment by Aenima4six2** [comment]
@Pliner Can we get this merged ?

**Comment by emanov** [comment]
Shouldn't be here the reconnection on exception when send?

**Comment by Aenima4six2** [comment]
@emanov We can definitely set the UDP client to null in a catch block surrounding the send call, but its not likely going to help anything if an exception were to throw. Since UDP is connectionless, recreating the client instance isn't actually "re-establishing" a connection. TCP, on the other hand, is a different story.

**Comment by emanov** [comment]
ok, thanks. Do you know the reason the branch was not merged to master yet?

**Comment by Pliner** [comment]
Thanks for the contributions, not sure the appveyour will publish to nuget sucessfully, but will fix it asap.

**Comment by emanov** [comment]
Great thanks for merging. The fix was published to nuget already an hour ago!

**Pull request merged**
